### ISSUE TITLE
Data Quality Engine

### ISSUE THREAD

**Issue by Abhairien** [AquaQProdSupport2/TorQ-Finance-Starter-Pack#11]
Write a process that checks the quality of on-disk data periodically.  Consider the following:
The checks should include, but are not limited to:
- [x] equal column counts
- [x] attributes have been applied (where set in schema)
- [x] enumeration files exist at the top level
- [x] An alarm should be raised in the event that any of the sanity checks fail, e.g. a mail detailing the failed checks.
- [ ] Unit tests
- [ ] Documentation

**Comment by jemmaborland** [comment]
Can you point me to where "enumeration files exist at the top level" is checked in your PR script? I can't see it but it's been ticked off above :wink:
