### ISSUE TITLE
Support Query for Georgia Goodspeed

### ISSUE THREAD

**Issue by JamesBurrows** [AquaQProdSupport2/TorQ-Finance-Starter-Pack#17]
I'm currently looking into data quality and I am interested in trading volume on an hourly basis, comparing the current trading day against the previous week.
I'd like a table showing me the average hourly counts from both trade and quote tables for the previous working week (Monday - Friday only), along with the hourly counts of the current trading day.

Ideally, I'd like the choice of inputting start and end dates or simply running without.
Specifying the dates which I wish to compare my current day with or I'd be able to simply run it without inputting the previous Monday & Friday, and it instead uses the current date to determine the previous Monday and Friday.

**Comment by Abhairien** [comment]
Hi Georgia,
if you run this through the gateway
.gw.syncexecj[({[t]$[`hdb~.proc.proctype;select avg prevol by sym,minute from select prevol:count i by date,sym,60 xbar time.minute from trade where date within t,not mod[date;7] in 0 1;select vol:count i by sym, 60 xbar time.minute from trade]};(2018.04.04;2018.04.14));`rdb`hdb;{x[1] lj x[0]}]
you should get a table with the hourly volume for today and the average for the previous days, you can modify the date range.

If you want to use the current date to determine the previous working week use -4 0+.z.d-(1+.z.d mod 7) as the date range:
.gw.syncexecj[({[t]$[`hdb~.proc.proctype;select avg prevol by sym,minute from select prevol:count i by date,sym,60 xbar time.minute from trade where date within t,not mod[date;7] in 0 1;select vol:count i by sym, 60 xbar time.minute from trade]};-4 0+.z.d-(1+.z.d mod 7));`rdb`hdb;{x[1] lj x[0]}]

regards,
prodsupport2
