### ISSUE TITLE
Query for specific trade

### ISSUE THREAD

**Issue by Abhairien** [AquaQProdSupport2/TorQ-Finance-Starter-Pack#18]
An efficient query to find a trade/record that occurred at a specific price for a specific sym at an exact time. This trade may have occurred yesterday or 10 years ago but is most likely to be found in recent partitions of a standard HDB.

**Comment by ThomasSmyth** [comment]
Is this still open?

**Comment by Abhairien** [comment]
Hi James,
you can use the following function, inputs are price,sym,time and the initial date you want to search from.
It works backwards until it finds the trade
```f:{[p;s;t;d] r:select from trade where date=d,sym=s,price=p,time=t; $[not count r;.z.s[p;s;t;d-1];r]}```

Thanks,
prodteam2
