### ISSUE TITLE
Orderbook, Symfile backup and Logfile Metrics

### ISSUE THREAD

**Issue by karanpatel12** [AquaQProdSupport2/TorQ-Finance-Starter-Pack#22]
Improvements to be made to the sym-file backup are as follows:

- [x] Confirm end of day backup is occurring correctly
- [x] Add in generation of backup directory

Improvements to the Logfile Metrics are to be made as follows:
- [x]    timestamps are replayed in order
- [x]   all of the records in the log are succesfully appended
- [x]   time spent reading the log
- [x]   time taken to replay log file
- [x]   distinct syms in log file

Improvements to the Orderbook are to be made as follows:
- [x]   Calculate best bid and offer in real time
- [x]   Provide tracking into to trace bbo records to quote which triggered record
- [x]   Must publish minimal records to not flood downstream clients
- [x]   Size changes of aggregated top of book size should be filtered
- [x]   Quotes older than x seconds are invalidated from orderbook
- [ ]    Replay functionality should not publish any records until correct table is attained.
- [x]   Relevant fields such as best bid and asc srcs should be included in bbo table.
- [x]   bbo table should be sent to RTD

**Comment by ThomasSmyth** [comment]
Assignment and label.
