### ISSUE TITLE
Detect Quote Stuffing 

### ISSUE THREAD

**Issue by lholmes8** [AquaQProdSupport2/TorQ-Finance-Starter-Pack#34]
Hi Prod Support Teams, 

I'd like a query to detect quote-stuffing (traders flooding the market with orders and then cancelling them to create 'noise' and influence other traders and therefore the market).

My input will ideally consist of;
table (this will usually be quote but could be quoteiex)
date in question
sym being looked into
the minimum number of movements that have to occur in our time period being checked
time period being checked (in seconds)

Kind Regards,
Marco Machiavelli

**Comment by lholmes8** [comment]
My 'time period' should perhaps rather be 'surge period', my quotes(from my desired date, sym and against the minimum number of specified price movements) should then be filtered by my 'surge period' xbar'd against time in seconds.

Let's say I run the function as;

getStuffed[`quote;2018.06.01;`AMD;60;5]

This will pull back POSSIBLE examples of quote stuffing for AMD on the 2018.06.01 that last at least 5 seconds and contained 60 adjustments to the top of the book.
This query returned a total of 2290 quotes which fell into my query stipulations.

Example output(standard quotes - as previosuly stated, further criteria was not required and this data would be used for analysis by others/prod support teams in the future);

date       time                          sym bid   ask   bsize asize mode ex
----------------------------------------------------------------------------
2018.06.01 2018.06.01D00:03:40.084279000 AMD 17.71 18.89 50    34    Y    N
2018.06.01 2018.06.01D00:03:40.084279000 AMD 18.02 18.7  29    50    A    N
2018.06.01 2018.06.01D00:03:40.084279000 AMD 18.08 18.8  98    64    R    N
2018.06.01 2018.06.01D00:03:41.284319000 AMD 18.15 18.54 75    46    A    N
2018.06.01 2018.06.01D00:03:41.284319000 AMD 18.23 18.39 92    49    Z    N
2018.06.01 2018.06.01D00:03:41.284319000 AMD 18.04 18.87 54    99    N    N
2018.06.01 2018.06.01D00:03:41.284319000 AMD 18.32 19.25 30    21    O    N
2018.06.01 2018.06.01D00:03:41.284319000 AMD 17.32 18.84 69    67    H    N

**Comment by shawjordan** [comment]
Hi Prod Support 2,

Any progress on this?

Thanks,
Marco

**Comment by lholmes8** [comment]
Hi Marco, 

Apologies for the delay. 
The below query should return possible examples of quote stuffing when given the parameters table,date,sym,minimum number of price movements to check, and the surge period over which you expect the stuffing to occur.

quotestuff:{[tbl;d;s;mvmt;t] select from tbl where date=d,sym=s, mvmt < ({sum differ x};bid) fby (t xbar time.second)}

You could then run this query as requested before:

quotestuff[`quote;2018.06.01;`AMD;60;5]

Regards,

Prod Support 2
