### ISSUE TITLE
Average price increase each sym

### ISSUE THREAD

**Issue by AquaQProdSupport2** [AquaQProdSupport2/TorQ-Finance-Starter-Pack#9]
Hi support
I'm looking to find the days where the average price went up for each sym?

Thanks in advance 
Ernest Evans

**Comment by karanpatel12** [comment]
````f:{[x] select date by sym from (select mean:avg[price] by sym,date from trade where date in .z.d-til[x]) where mean>prev[mean]}````

Hello Ernest Evans,
The above function where x is the number of days you would like to examine should give you the dates where the average has increased relative to the previous day.

Regards
Prodsupport2

**Comment by JuliaPartridge** [comment]
Hi Ernest Evans,

Here is a query that will allow you to find the days where the average price went up for each sym:

`f:{[x] select date by sym from (select mean:avg price by sym,date from trade where date in .z.d-til x) where mean>prev mean}`

This function requires an input of the number of days you would like to query prior to the current date. It will return a keyed table by sym with the dates where the average price increased.

Hope this

**Comment by claire-sloan** [comment]
Thanks, much appreciated!
